import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/query-client";
import { VehicleContextProvider } from "@/providers/vehicle-provider";
import { Toaster } from "./(dashboard)/_components/ui/sonner";
import { UserContextProvider } from "@/providers/user-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Atribs | Interview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReactQueryProvider>
          <UserContextProvider>
            <VehicleContextProvider>
              <Toaster />
              {children}
            </VehicleContextProvider>
          </UserContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
